### ISSUE TITLE
crash : com.tealium.library.I.onTouchEvent

### ISSUE THREAD

**Issue by kendrick-k** [Tealium/android-library#7]
http://crashes.to/s/337b803abaa

**Comment by ChadHartman** [comment]
Tealium performs UI auto-tracking by subscribing to touch events, and then send them off to their intended recipients; this is why we are present in the stack trace. MotionEvents are not mutated in any way by this system. 

Are you able to replicate the issue?

**Comment by drschilling** [comment]
It is possible to disable an UI auto-tracking dispatch for a view? Even using the full version?

**Comment by ChadHartman** [comment]
You can exclude activities from auto-tracking by using [this api](https://github.com/Tealium/android-library/wiki/API-Tealium.Config#tealiumconfig-setexcludedactivityclassessetclass-extends-activity-excludedactivityclasses) otherwise you can completely turn off UI auto-tracking in the publish settings.
